[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brainmesh"
version = "0.0.1"
description = "Create tetrahedral brain meshes from segmentations"
authors = [{ name = "Marius Causemann", email = "mariusca@simula.no" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "nibabel",
    "pyvista",
    "nbmorph",
    "pytetwild",
    "libigl",
    "edt",
    "fastremap",
    "scikit-image",
    "scipy",
    "numba",
    "connected-components-3d",
    "vtk>=9.6",
    "matplotlib",
    "meshio",
    "h5py",
    "tomlkit",
    "tqdm
]

[project.urls]
homepage = "https://github.com/MariusCausemann/brainmesh"

[project.scripts]
brainmesh-surface = "brainmesh.cli:surface_main"
brainmesh-mesh = "brainmesh.cli:mesh_main"
brainmesh-subdivideSAS = "brainmesh.cli:subdivide_SAS"
brainmesh-curve-mesh = "brainmesh.cli:curve_mesh_main"
brainmesh-mark-facets = "brainmesh.cli:mark_facets_main"
brainmesh-remark-sas = "brainmesh.cli:remark_sas_main"
brainmesh-extract-csf = "brainmesh.cli:extract_csf_main"
brainmesh-group-regions = "brainmesh.cli:group_regions_main"
brainmesh-plot-mesh = "brainmesh.cli:plot_mesh_main"
brainmesh-plot-facets = "brainmesh.cli:plot_facets_main"


[project.optional-dependencies]
dev = ["pdbpp", "ipython", "mypy", "ruff", "pytest"]
docs = [
    "jupyter-book<2.0.0",
    "jupytext",
    "ipykernel<7.0.0",
    "sphinx-codeautolink",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]
markers = ["slow: marks tests as slow (deselect with '-m not slow')"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["docs/", "build/"]
files = ["src", "tests"]

[tool.ruff]
src = ["src", "tests"]
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = ["F", "E", "W", "I001"]

[tool.ruff.lint.isort]
known-first-party = ["brainmesh"]
known-third-party = ["numpy", "pytest"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
